In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [41]:
dataset = pd.read_csv('dataindustripariwisatajakarta.csv')
x = dataset.iloc[:, :7].values


In [42]:
print(x)

[['JAKARTA PUSAT' 205 29571 224 1259 402]
 ['JAKARTA UTARA' 59 7420 285 937 134]
 ['JAKARTA BARAT' 104 11476 300 742 180]
 ['JAKARTA TIMUR' 29 3010 88 262 334]
 ['JAKARTA SELATAN ' 119 16515 390 2204 698]]


In [43]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [44]:
print(x)

[[0.0 1.0 0.0 0.0 0.0 205 29571 224 1259 402]
 [0.0 0.0 0.0 0.0 1.0 59 7420 285 937 134]
 [1.0 0.0 0.0 0.0 0.0 104 11476 300 742 180]
 [0.0 0.0 0.0 1.0 0.0 29 3010 88 262 334]
 [0.0 0.0 1.0 0.0 0.0 119 16515 390 2204 698]]


In [45]:
from sklearn.model_selection import train_test_split
x_train, x_test = train_test_split(x, test_size = 0.2, random_state=1)

In [46]:
print(x_train)

[[0.0 0.0 0.0 0.0 1.0 59 7420 285 937 134]
 [0.0 0.0 1.0 0.0 0.0 119 16515 390 2204 698]
 [0.0 1.0 0.0 0.0 0.0 205 29571 224 1259 402]
 [0.0 0.0 0.0 1.0 0.0 29 3010 88 262 334]]


In [47]:
print(x_test)

[[1.0 0.0 0.0 0.0 0.0 104 11476 300 742 180]]


In [49]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 5:] = sc.fit_transform(x_train[:, 5:])
x_test[:, 5:] = sc.transform(x_test[:, 5:])

In [50]:
print(x_train)

[[0.0 0.0 0.0 0.0 1.0 -0.6546053692602627 -0.6604235803985495
  0.3502593416403612 -0.326783140095236 -1.2754784372596666]
 [0.0 0.0 1.0 0.0 0.0 0.23803831609464096 0.23487414858115058
  1.3117555735942938 1.4851828927304274 1.5127767511684418]
 [0.0 1.0 0.0 0.0 0.0 1.517494265103336 1.5200865894342528
  -0.20832418359001875 0.13371651465603757 0.04943714873099483]
 [0.0 0.0 0.0 1.0 0.0 -1.1009272119377145 -1.0945371576168539
  -1.4536907316446364 -1.292116267291229 -0.28673546263977]]


In [51]:
print(x_test)

[[1.0 0.0 0.0 0.0 0.0 104.0 11476.0 300.0 742.0 180.0]]
